routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

    Route::group(['middleware' => ['guest:admin', 'prevent-back-history']], function(){
        Route::get('/', 'LoginController@showLoginForm')->name('show.login');
        Route::post('/', 'LoginController@loginForm')->name('login');
        Route::get('forgot-password', 'ForgotPasswordController@showForgotPassword')->name('show.forgot.password');
        Route::post('forgot-password', 'ForgotPasswordController@forgotPassword')->name('forgot.password');
        Route::get('reset-password/{token}', 'RestPasswordController@showResetPassword')->name('show.reset.password');
        Route::post('reset-password', 'RestPasswordController@resetPassword')->name('reset.password');
    });

    Route::group(['middleware' => ['auth:admin', 'prevent-back-history']],function(){
        Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
        Route::post('logout','LoginController@logout')->name('logout');
        Route::get('change-password','ChangePasswordController@showChangePassword')->name('show.change.password');
        Route::post('change-password','ChangePasswordController@changePassword')->name('change.password');
        Route::get('edit-profile','ProfileController@editProfileShow')->name('profile.edit.show');
        Route::post('edit-profile','ProfileController@editProfile')->name('profile.edit');
        
        //User Management Route
        Route::get('user-management/list', 'UserManagementController@userList')->name('user.list');
        Route::get('user-management/add', 'UserManagementController@userAddView')->name('user.add.view');
        Route::post('user-management/add', 'UserManagementController@userAdd')->name('user.add');
        Route::get('user-management/edit/{id}/{page?}', 'UserManagementController@userEditView')->name('user.edit.view');
        Route::post('user-management/edit/{id}/{page?}', 'UserManagementController@userEdit')->name('user.edit');
        Route::get('user-management/delete/{id}/{page?}', 'UserManagementController@userDelete')->name('user.delete');
        Route::get('user-management/view/{id}/{page?}', 'UserManagementController@userView')->name('user.view');
        
        
        


    });
});

resources/views/admin/dashboard.blade.php
@extends('admin.include.layouts')
@section('content')
<div class="content-wrapper">
    <div class="row">
      <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-body performane-indicator-card">
              <img src="https://i.pinimg.com/originals/eb/c6/a7/ebc6a7c40fa59d1389efa2c35ade9930.jpg" style="width: 100%; height: 372px">
          </div>
        </div>
      </div>
    </div>
</div>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from www.bootstrapdash.com/demo/stellar-admin/jquery/template/demo_1/pages/samples/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 03 Dec 2020 05:41:10 GMT -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Style Hawk</title>
    @toastr_css
    <!-- plugins:css -->
    <link rel="stylesheet" href="{{asset('public/assets/vendors/simple-line-icons/css/simple-line-icons.css')}}">
    <link rel="stylesheet" href="{{asset('public/assets/vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/assets/vendors/css/vendor.bundle.base.css')}}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{{asset('public/assets/css/demo_1/style.css')}}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{{asset('public/assets/images/favicon.png')}}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        .error {
            color: red;
        }
    </style>
</head>
<body>
@jquery
@toastr_js
@toastr_render
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth">
            <div class="row flex-grow">
                <div class="col-lg-4 mx-auto">
                    <div class="auth-form-light text-left p-5">
                        <div class="brand-logo" style="text-align: center">
                            <img src="{{asset('public/storage/uploads/project-logo/stylhawklogo.png')}}" alt="logo" class="logo-dark"style="width: 65px; height: 60px; "/>
                        </div>
                        <h4>Admin Login Form</h4>
                        <h6 class="font-weight-light">Sign in to continue.</h6>
                        <form class="pt-3" method="POST" action="{{ route('admin.login') }}" id="admin-login-form" autocomplete="off">
                            @csrf
                            <div class="form-group">
                                <input id="email" type="text" class="form-control form-control-lg @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" autocomplete="email" autofocus placeholder="Email">
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <input id="password" type="password" class="form-control form-control-lg @error('password') is-invalid @enderror" name="password" autocomplete="current-password" placeholder="Password">
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                            <div class="mt-3">
                                <button type="submit" id="submit" class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">
                                    SIGN IN <i class="fa fa-refresh fa-spin" style="display: none" id="spinner"></i>
                                </button>
                            </div>
                            <div class="my-2 d-flex justify-content-between align-items-center">
{{--                                <div class="form-check">--}}
{{--                                    <label class="form-check-label text-muted">--}}
{{--                                        <input type="checkbox" class="form-check-input" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}> Keep me signed in </label>--}}
{{--                                </div>--}}
                                <div></div>
                                    <a class="auth-link text-black" href="{{ route('admin.show.forgot.password') }}">
                                        Forgot password?
                                    </a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script src="{{asset('public/assets/vendors/js/vendor.bundle.base.js')}}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{{asset('public/assets/js/off-canvas.js')}}"></script>
<script src="{{asset('public/assets/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('public/assets/js/misc.js')}}"></script>
<script src="{{asset('public/assets/js/settings.js')}}"></script>
<script src="{{asset('public/assets/js/todolist.js')}}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<script src="{{asset('public/stylehawk/validation.js')}}"></script>
<!-- endinject -->
</body>
<!-- Mirrored from www.bootstrapdash.com/demo/stellar-admin/jquery/template/demo_1/pages/samples/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 03 Dec 2020 05:41:10 GMT -->
</html>