routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

    Route::group(['middleware' => ['guest:admin', 'prevent-back-history']], function(){
        Route::get('/', 'LoginController@showLoginForm')->name('show.login');
        Route::post('/', 'LoginController@loginForm')->name('login');
        Route::get('forgot-password', 'ForgotPasswordController@showForgotPassword')->name('show.forgot.password');
        Route::post('forgot-password', 'ForgotPasswordController@forgotPassword')->name('forgot.password');
        Route::get('reset-password/{token}', 'RestPasswordController@showResetPassword')->name('show.reset.password');
        Route::post('reset-password', 'RestPasswordController@resetPassword')->name('reset.password');
    });

    Route::group(['middleware' => ['auth:admin', 'prevent-back-history']],function(){
        Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
        Route::post('logout','LoginController@logout')->name('logout');
        Route::get('change-password','ChangePasswordController@showChangePassword')->name('show.change.password');
        Route::post('change-password','ChangePasswordController@changePassword')->name('change.password');
        Route::get('edit-profile','ProfileController@editProfileShow')->name('profile.edit.show');
        Route::post('edit-profile','ProfileController@editProfile')->name('profile.edit');
        
        //User Management Route
        Route::get('user-management/list', 'UserManagementController@userList')->name('user.list');
        Route::get('user-management/add', 'UserManagementController@userAddView')->name('user.add.view');
        Route::post('user-management/add', 'UserManagementController@userAdd')->name('user.add');
        Route::get('user-management/edit/{id}/{page?}', 'UserManagementController@userEditView')->name('user.edit.view');
        Route::post('user-management/edit/{id}/{page?}', 'UserManagementController@userEdit')->name('user.edit');
        Route::get('user-management/delete/{id}/{page?}', 'UserManagementController@userDelete')->name('user.delete');
        Route::get('user-management/view/{id}/{page?}', 'UserManagementController@userView')->name('user.view');
        
        
        


    });
});

resources/views/admin/include/footer.blade.php
<!-- partial:partials/_footer.html -->
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2019 Stellar. All rights reserved. <a href="#"> Terms of use</a><a href="#">Privacy Policy</a></span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="text-danger"></i></span>
    </div>
</footer>
<!-- partial -->

resources/views/admin/include/header.blade.php
<!-- partial:partials/_navbar.html -->
<nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="{{route('admin.dashboard')}}">
            <img src="{{asset('public/storage/uploads/project-logo/stylhawklogo.png')}}" alt="logo" class="logo-dark"/>
        </a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center">
        <h5 class="mb-0 font-weight-medium d-none d-lg-flex">{{$title ?? ''}}</h5>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown d-none d-xl-inline-flex user-dropdown">
                <a class="nav-link" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                    @if(auth('admin')->user()->image)
                        <img class="img-xs rounded-circle ml-2" src="{{asset('public/storage/uploads/users/'. auth('admin')->user()->image ?? 'avtar.png')}}" alt="Profile image"> </a>
                    @else
                        <img class="img-xs rounded-circle ml-2" src="{{asset('public/storage/uploads/users/avtar.png')}}" alt="Profile image"> </a>
                    @endif
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                    <div class="dropdown-header text-center">
                        @if(auth('admin')->user()->image)
                            <img class="img-md rounded-circle" src="{{asset('public/storage/uploads/users/'. auth('admin')->user()->image ?? '')}}" alt="Profile image" style="height: 50px; width:50px">
                        @else
                            <img class="img-xs rounded-circle ml-2" src="{{asset('public/storage/uploads/users/avtar.png')}}" alt="Profile image"> </a>
                        @endif
                        <p class="mb-1 mt-3">{{ \Illuminate\Support\Str::limit(ucfirst(auth('admin')->user()->name ?? ''), 15, $end='...')}}</p>
                        <p class="font-weight-light text-muted mb-0">{{auth('admin')->user()->email ?? ''}}</p>
                    </div>
                    <a class="dropdown-item" href="{{route('admin.profile.edit.show')}}"><i class="dropdown-item-icon fa fa-user text-primary"></i> My Profile</a>
                    <a class="dropdown-item" href="{{route('admin.show.change.password')}}"><i class="dropdown-item-icon fa fa-unlock text-primary"></i>Change Password</a>
                    @guest
                    <a class="dropdown-item" href="{{route('admin.login.show')}}"><i class="dropdown-item-icon icon-powerfa fa-sign-in text-primary"></i>Login</a>
                        @if (Route::has('register'))
                            <a class="dropdown-item" href="{{route('register')}}"><i class="dropdown-item-icon icon-power text-primary"></i>Register</a>
                        @endif
                        @else
                        <a class="dropdown-item" href="{{ route('admin.logout') }}" onclick="event.preventDefault();
                                                             document.getElementById('logout-form').submit();">
                            <i class="dropdown-item-icon fa fa-sign-out text-primary"></i>Logout
                                <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                        </a>
                    @endguest
                </div>
            </li>
        </ul>
    </div>
</nav>
<!-- partial -->

resources/views/admin/include/layouts.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Style Hawk</title>
    @toastr_css
    <!-- plugins:css -->

    <link rel="stylesheet" href="{{asset('public/assets/vendors/flag-icon-css/css/flag-icon.min.css')}}">
    <link rel="stylesheet" href="{{asset('public/assets/vendors/css/vendor.bundle.base.css')}}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="{{asset('public/assets/vendors/jvectormap/jquery-jvectormap.css')}}">
    <link rel="stylesheet" href="{{asset('public/assets/vendors/daterangepicker/daterangepicker.css')}}">
{{--    <link rel="stylesheet" href="{{asset('public/assets/vendors/chartist/chartist.min.css')}}">--}}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.5.5/css/simple-line-icons.min.css">
    <link rel="stylesheet" href="{{asset('public/assets/css/demo_1/style.css')}}">
    <link rel="shortcut icon" href="{{asset('public/assets/images/favicon.png')}}" />
    <link rel="stylesheet" href="{{asset('public/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css')}}">
    <style>
        .error
        {
            color: red;
        }
        .dataTables_wrapper .dataTables_length select {
            height: auto;
        }
        .select2-container--default .select2-selection--single .select2-selection__rendered{
            margin: -16px;
        }
        .select2-container--default .select2-selection--single {
            padding-top: 20px;

        }

        #all-scroll {cursor: all-scroll;}

    </style>
</head>
<body>
<div class="container-scroller">
    <!-- partial:partials/_navbar.html -->
    @include('admin.include.header')
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
        <!-- partial:partials/_settings-panel.html -->
        <!-- partial -->
        <!-- partial:partials/_sidebar.html -->
        @include('admin.include.sidebar')
        <!-- partial -->
        <div class="main-panel">
            @jquery
            @toastr_js
            @toastr_render
            @yield('content')
            <!-- content-wrapper ends -->
            <!-- partial:partials/_footer.html -->
            @include('admin.include.footer')
            <!-- partial -->
        </div>
        <!-- main-panel ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script src="{{asset('public/assets/vendors/js/vendor.bundle.base.js')}}"></script>
<!-- endinject -->
<!-- Plugin js for this page -->
<script src="{{asset('public/assets/vendors/chart.js/Chart.min.js')}}"></script>
<script src="{{asset('public/assets/vendors/jvectormap/jquery-jvectormap.min.js')}}"></script>
<script src="{{asset('public/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>


<script src="{{asset('public/assets/vendors/moment/moment.min.js')}}"></script>
<script src="{{asset('public/assets/vendors/daterangepicker/daterangepicker.js')}}"></script>

{{--<script src="{{asset('public/assets/vendors/chartist/chartist.min.js')}}"></script>--}}
<script src="{{asset('public/assets/vendors/progressbar.js/progressbar.min.js')}}"></script>
<!-- End plugin js for this page -->
<!-- inject:js -->
<script src="{{asset('public/assets/js/off-canvas.js')}}"></script>
<script src="{{asset('public/assets/js/hoverable-collapse.js')}}"></script>
<script src="{{asset('public/assets/js/misc.js')}}"></script>
<script src="{{asset('public/assets/js/settings.js')}}"></script>
<script src="{{asset('public/assets/js/todolist.js')}}"></script>
<!-- endinject -->
<!-- Custom js for this page -->
{{--<script src="{{asset('public/assets/js/dashboard.js')}}"></script>--}}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.23/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.js"></script>

<script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.5.9/adapters/jquery.js"></script>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.js"></script>

<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/additional-methods.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>

<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css">

<script src="{{asset('public/assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js')}}"></script>

@yield('scripts')
</body>
</html>

resources/views/admin/include/sidebar.blade.php
<!-- partial:partials/_settings-panel.html -->
{{--<div id="settings-trigger"><i class="icon-settings"></i></div>--}}
<div id="theme-settings" class="settings-panel">
    <i class="settings-close icon-close"></i>
    <p class="settings-heading">SIDEBAR SKINS</p>
    <div class="sidebar-bg-options selected" id="sidebar-default-theme">
        <div class="img-ss rounded-circle bg-dark border mr-3"></div>Default
    </div>
    <div class="sidebar-bg-options" id="sidebar-light-theme">
        <div class="img-ss rounded-circle bg-light border mr-3"></div>Light
    </div>
    <p class="settings-heading mt-2">HEADER SKINS</p>
    <div class="color-tiles mx-0 px-4">
        <div class="tiles dark"></div>
        <div class="tiles default light"></div>
    </div>
</div>
<!-- partial -->
<!-- partial:partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="profile-image">
                    @if(auth('admin')->user()->image)
                    <img class="img-xs rounded-circle" src="{{asset('public/storage/uploads/users/'. auth('admin')->user()->image ?? '')}}" alt="profile image">
                    @else
                        <img class="img-xs rounded-circle" src="{{asset('public/storage/uploads/users/avtar.png')}}" alt="profile image">
                    @endif
                </div>
                <div class="text-wrapper">
                    <p class="profile-name">{{ \Illuminate\Support\Str::limit(ucfirst(auth('admin')->user()->name ?? ''), 15, $end='...')}}</p>
                    <p class="designation">{{auth('admin')->user()->email ?? ''}}</p>
                </div>
            </a>
        </li>
        <li class="nav-item nav-category"><a class="nav-link" href="{{route('admin.dashboard')}}">Dashboard</a></li>
        @php
            $admin_menu_active = Request::segment('2');
        @endphp

        <li class="nav-item ">
            
                <a class="nav-link {{$admin_menu_active ? ""  :"collapsed"}}" data-toggle="collapse" href="#" aria-expanded="{{$admin_menu_active ? "true" : "false"}}" aria-controls="ui-basic">
                    <span class="menu-title">Admin</span>
                    <i class="fa fa-user-circle-o menu-icon"></i>
                </a>
           
                <div class="collapse {{$admin_menu_active ? "show" : ""}}" id="ui-basic">
                    <ul class="nav flex-column sub-menu">
                        <li class="nav-item"> <a class="nav-link {{$admin_menu_active == 'user-management'? 'active' : 'unactive'}}" href="{{route('admin.user.list')}}">Employee Management</a></li>
                        
                    </ul>
                </div>
            </li>

            
        </ul>
</nav>