routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/
Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function(){

    Route::group(['middleware' => ['guest:admin', 'prevent-back-history']], function(){
        Route::get('/', 'LoginController@showLoginForm')->name('show.login');
        Route::post('/', 'LoginController@loginForm')->name('login');
        Route::get('forgot-password', 'ForgotPasswordController@showForgotPassword')->name('show.forgot.password');
        Route::post('forgot-password', 'ForgotPasswordController@forgotPassword')->name('forgot.password');
        Route::get('reset-password/{token}', 'RestPasswordController@showResetPassword')->name('show.reset.password');
        Route::post('reset-password', 'RestPasswordController@resetPassword')->name('reset.password');
    });

    Route::group(['middleware' => ['auth:admin', 'prevent-back-history']],function(){
        Route::get('dashboard', 'DashboardController@dashboard')->name('dashboard');
        Route::post('logout','LoginController@logout')->name('logout');
        Route::get('change-password','ChangePasswordController@showChangePassword')->name('show.change.password');
        Route::post('change-password','ChangePasswordController@changePassword')->name('change.password');
        Route::get('edit-profile','ProfileController@editProfileShow')->name('profile.edit.show');
        Route::post('edit-profile','ProfileController@editProfile')->name('profile.edit');
        
        //User Management Route
        Route::get('user-management/list', 'UserManagementController@userList')->name('user.list');
        Route::get('user-management/add', 'UserManagementController@userAddView')->name('user.add.view');
        Route::post('user-management/add', 'UserManagementController@userAdd')->name('user.add');
        Route::get('user-management/edit/{id}/{page?}', 'UserManagementController@userEditView')->name('user.edit.view');
        Route::post('user-management/edit/{id}/{page?}', 'UserManagementController@userEdit')->name('user.edit');
        Route::get('user-management/delete/{id}/{page?}', 'UserManagementController@userDelete')->name('user.delete');
        Route::get('user-management/view/{id}/{page?}', 'UserManagementController@userView')->name('user.view');
        
        
        


    });
});

app/UserManagement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;

class UserManagement extends Model
{
    //use HasApiTokens, Notifiable;

    protected $guarded = [];

    protected $hidden = ['password'];

    public function countries()
    {
        return $this->belongsTo(Country::class,'country_id', 'id');
    }

    public function cities()
    {
        return $this->belongsTo(City::class,'city_id', 'id');
    }

    public function states()
    {
        return $this->belongsTo(State::class,'state_id', 'id');
    }

    public function shippingAddress(){
        return $this->hasOne(ShippingAddress::class,'user_id', 'id');
    }

    public function billingAddress(){
        return $this->hasOne(BillingAddress::class, 'user_id', 'id');
    }


}

app/Http/Controllers/Admin/UserManagementController.php
<?php

namespace App\Http\Controllers\Admin;

use App\City;
use App\Country;
use App\EmailTemplate;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserManagementAddRequest;
use App\Http\Requests\UserManagementEditRequest;
use App\State;
use App\UserManagement;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class UserManagementController extends Controller
{
    //Function For Fetch All Employee Record With Variation Fillter
    public function userList(Request $request)
    {
        $title = "User List";
        $user_list = UserManagement::query();
        //Start To End Date Fillter
        if (!empty($request->from) && !empty($request->to)){
            $from = Carbon::createFromFormat("m/d/Y", $request->from)->format("Y-m-d");
            $to = Carbon::createFromFormat("m/d/Y", $request->to)->format("Y-m-d");
            $user_list = $user_list->whereDate('created_at', '>=', $from)
                                    ->whereDate('created_at', '<=', $to);
            }
        //End Fillter Of Start Or End Date

        //Start Full Name Fillter
        if(!empty(trim($request->full_name))){
           $user_list = $user_list->where('full_name', 'LIKE', '%'.trim($request['full_name']).'%'); 
        }
        //End Full Name fillter

        //Start Email Fillter
        if(!empty(trim($request->email))){
            $user_list = $user_list->where('email', 'LIKE', '%'.trim($request['email']).'%'); 
         }
        //End Email Fillter
         if(!empty(trim($request->phone_number))){
            $user_list = $user_list->where('phone_number', 'LIKE', '%'.trim($request['phone_number']).'%'); 
         }
         //End Email Fillter

         //Start Status Wise Filtter 
         if(isset($request->status)){
            $user_list = $user_list->where('status', $request['status']); 
        }
        //End Status Wise Fillter
         
        //Fetch Record According To Condition
        $user_list = $user_list->orderBy('created_at', 'desc')->paginate(50);

        //Compact Data In View File
        return view("admin.user-management.list", compact('title', 'user_list'));
    }

    //Load Add Employee Form Function
    public function userAddView()
    {
        $title = "Emplyee Add Form";
        return view('admin.user-management.add', compact('title'));
    }
    //End Add Employee Form Function



    //Add Employee Record Function Start
    //Validation Checked In UserManagementAddRequest File & This File In Request Folder
    public function userAdd(UserManagementAddRequest $request)
    {
        $user_management = new UserManagement();
        $user_management->full_name = $request['full_name'];
        $user_management->phone_number = $request['phone_number'];
        $user_management->email = $request['email'];
        $user_management->dob = $request['dob'];
        $user_management->status = $request['status'];
        $user_management->password = Hash::make($request['password']);
        if ($request->hasFile('image')) {
                $file = $request->file('image');
                $destinationPath = 'public/storage/uploads/user-management/';
                $extension = $request->file('image')->getClientOriginalExtension();
                $filename =  time(). '.' . $extension;
                $file->move($destinationPath, $filename);
            $user_management->image = $filename;
            }
        $user_management->save();
        toastr()->success('User successfully added!');
        return redirect()->route('admin.user.list');
    }
    //Add Employee Record Function End

    //Load Edit Emplyee Form Start
    public function userEditView(Request $request, $id)
    {
        $title = "Emplyee Edit Form";
        $edit = UserManagement::find(base64_decode($id));
        return view('admin.user-management.edit', compact('title', 'edit'));
    }
    //Load Edit Emplyee Form End



    //Edit Employee Record Function Start
    //Validation Checked In UserManagementAddRequest File & This File In Request Folder
    public function userEdit(UserManagementEditRequest $request, $id, $page=null)
    {
        $edit = UserManagement::find(base64_decode($id));
        if ($edit)
        {
            $edit->full_name = $request['full_name'];
            $edit->phone_number = $request['phone_number'];
            $edit->email = $request['email'];
            $edit->dob = $request['dob'];
            $edit->status = $request['status'];
            if ($request->hasFile('image')) {
                $file = $request->file('image');
                $destinationPath = 'public/storage/uploads/user-management/';
                $extension = $request->file('image')->getClientOriginalExtension();
                $filename =  time(). '.' . $extension;
                $file->move($destinationPath, $filename);
                $edit->image = $filename;
            }
            if ($request->has('password'))
            {
                $edit->password = Hash::make($request['password']);
            }
            $edit->save();
            toastr()->success('User successfully updated!');
            return redirect('admin/user-management/list?page='.$page);
        }
        else{
            toastr()->error('Something went wrong!');
            return redirect()->route('admin/user-management/list?page='.$page);
        }
    }
    //Edit Employee Record Function End

    //Record delete function
    public function userDelete(Request $request, $id, $page=null)
    {
        $delete = UserManagement::findOrFail(base64_decode($id));

        //If id received in valid then checked if condition otherwise checked else condition
        if ($delete)
        {
            $delete->delete();
            toastr()->success('User successfully deleted!');
            return redirect('admin/user-management/list?page='.$page);
        }
        else{
            toastr()->error('Something went wrong!');
            return redirect('admin/user-management/list?page='.$page);
        }

    }


}

resources/views/admin/user-management/add.blade.php
@extends('admin.include.layouts')
@section('content')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> </h3>
            <nav aria-label="breadcrumb">
                <a class="btn btn-success btn-fw" href="{{route('admin.user.list')}}"><i class="fa fa-backward"></i>  Back</a>
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form class="cmxform" id="user-management-add-form" method="post" action="{{route('admin.user.add')}}" autocomplete="off" enctype="multipart/form-data">
                            @csrf
                            <fieldset>
                                <div class="form-group">
                                    <label for="first_name">Full Name
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="first_name" class="form-control @error('full_name') is-invalid @enderror" value="{{ old('full_name') }}" name="full_name" type="text" placeholder="Full Name">
                                    @error('full_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="email">Email
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" type="text" placeholder="Email Address">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="phone_number">Phone Number
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="phone_number" class="form-control @error('phone_number') is-invalid @enderror" value="{{ old('phone_number') }}" name="phone_number" type="text" placeholder="Phone Number">
                                    @error('phone_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="location">Date Of Birth
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="dob" class="form-control @error('dob') is-invalid @enderror" value="{{ old('dob') }}" name="dob" type="text" placeholder="Select Date Of Birth">
                                    @error('dob')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="password">Password
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="password" class="form-control @error('password') is-invalid @enderror password" name="password" type="password" placeholder="Password">
                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="password_confirmation">Confirm password
                                        <span class="required-asterisk" style="color: red"> * </span>
                                    </label>
                                    <input id="password_confirmation" class="form-control password" name="password_confirmation" type="password" placeholder="Confirm password">
                                </div>
                                <div class="form-group">
                                    <label for="password_confirmation">Image
                                        <span class="required-asterisk" style="color: red"> * </span>
                                    </label>
                                    <input id="image" class="form-control password @error('image') is-invalid @enderror" name="image" type="file" placeholder="Select Image">
                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="status">Status
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="status" id="active" value="1" checked> Active </label>
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="status" id="inactive" value="0"> Inactive </label>
                                    </div>
                                </div>

                                <button class="btn btn-primary" type="submit">Submit <i class="fa fa-refresh fa-spin" style="display: none" id="spinner"></i></button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('public/stylehawk/validation.js')}}"></script>
    <script type="text/javascript">
        $(document).ready( function () {

            $('#dob').datepicker({
                uiLibrary: 'bootstrap4'
            });
        });
    </script>

@endsection

resources/views/admin/user-management/edit.blade.php
@extends('admin.include.layouts')
@section('content')
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <form class="cmxform" id="user-management-edit-form" method="post" action="{{route('admin.user.edit', ['id'=>base64_encode($edit->id), 'page'=>request('page')])}}" autocomplete="off" enctype="multipart/form-data">
                            @csrf
                            <fieldset>
                                <div class="form-group">
                                    <label for="first_name">Full Name
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="first_name" class="form-control @error('full_name') is-invalid @enderror" value="{{$edit->full_name ?? ''}}" name="full_name" type="text" placeholder="Full Name">
                                    @error('full_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="email">Email
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{$edit->email ?? ''}}" type="text" placeholder="Email Address">
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="phone_number">Phone Number
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="phone_number" class="form-control @error('phone_number') is-invalid @enderror" value="{{$edit->phone_number ?? ''}}" name="phone_number" type="text" placeholder="Phone Number">
                                    @error('phone_number')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="location">Date Of Birth
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="dob" class="form-control @error('dob') is-invalid @enderror" value="{{$edit->dob ?? ''}}" name="dob" type="text" placeholder="Select Date Of Birth">
                                    @error('dob')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="password">Password
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <input id="password" class="form-control @error('password') is-invalid @enderror password" name="password" type="password" placeholder="Password">
                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="password_confirmation">Confirm password
                                        <span class="required-asterisk" style="color: red"> * </span>
                                    </label>
                                    <input id="password_confirmation" class="form-control password" name="password_confirmation" type="password" placeholder="Confirm password">
                                </div>
                                <div class="form-group">
                                    <label for="password_confirmation">Image
                                        <span class="required-asterisk" style="color: red"> * </span>
                                    </label>
                                    <input id="image" class="form-control password @error('image') is-invalid @enderror" name="image" type="file" placeholder="Select Image">
                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    @if($edit->image)
                                        <img src="{{asset('public/storage/uploads/user-management/'.$edit->image ?? '')}}" style="height: 50px; width: 50px;">
                                    @else
                                        <img src="{{asset('public/storage/uploads/user-management/avtar.png')}}" style="height: 50px; width: 50px;">
                                    @endif

                                </div>
                                <div class="form-group">
                                    <label for="status">Status
                                        <span class="required-asterisk" style="color: red">*</span>
                                    </label>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="status" id="active" value="1" {{$edit->status === 1 ? 'checked' : ''}}> Active </label>
                                    </div>
                                    <div class="form-check">
                                        <label class="form-check-label">
                                            <input type="radio" class="form-check-input" name="status" id="inactive" value="0" {{$edit->status === 0 ? 'checked' : ''}}> Inactive </label>
                                    </div>
                                </div>
                                <button class="btn btn-primary" type="submit">Submit <i class="fa fa-refresh fa-spin" style="display: none" id="spinner"></i></button>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('public/stylehawk/validation.js')}}"></script>
    <script type="text/javascript">
        $(document).ready( function () {

            $('#dob').datepicker({
                uiLibrary: 'bootstrap4'
            });
        });
    </script>

@endsection

resources/views/admin/user-management/list.blade.php
@extends('admin.include.layouts')
@section('content')

<div class="content-wrapper">
    <div class="row">
            <div class="col-lg-12">
        <div class="col-2 grid-margin stretch-card">

            <a class="btn btn-success btn-fw" href="{{route('admin.user.add.view')}}"><i class="fa fa-plus"></i>  Create</a>

        </div>
        <form action="{{route('admin.user.list')}}" method="get">

            <div class="col-8 grid-margin stretch-card">
                <input type="text" name="full_name" placeholder="Full Name" id="full_name" value="{{ request('full_name') }}">
                <input type="text" name="email" placeholder="Email" id="email" value="{{ request('email') }}">
                <input type="text" name="phone_number" placeholder="Phone Number" id="phone_number" value="{{ request('phone_number') }}">
                
            </div>
            <div class="col-8 grid-margin stretch-card">
                <input type="text" id="from" name="from" value="{{request('from') ?? ''}}" placeholder="From Date">&nbsp;&nbsp;
                <input type="text" id="to" name="to" value="{{request('to') ?? ''}}" placeholder="To Date"> &nbsp;&nbsp;
                
                <select name="status" id="status">
                  <option value="">Select status {{request('status')}}</option>
                  <option value="1" {{request('status') == 1 ? 'selected' : ''}}>Active</option>
                  <option value="0" {{request('status') == 0 ? 'selected' : ''}}>InActive</option>
                </select>
                <br><br>
                &nbsp;&nbsp;&nbsp;
                <button type="submit" class="btn btn-success btn-sm">Filter</button> &nbsp;&nbsp;
                <a href="{{ route('admin.user.list') }}"><button type="button" id="reset" class="btn btn-primary btn-sm">Reset</button></a>
            </div>
        </form>
    </div>
</div>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-12">
                    <div class="table-responsive">
                        <table id="data-table-id" class="table">
                            <thead>
                                <tr>
                                    <th>S.No</th>
                                    <th>Full Name</th>
                                    <th>Phone Number</th>
                                    <th>Email</th>
                                    <th>Date</th>
                                    <th>Image</th>
                                    <th>DOB</th>
                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($user_list as $key => $user_data)
                                <tr>
                                    <td>{{$user_list->firstItem() + $key}}</td>
                                    <td>{{ucfirst($user_data->full_name)}}</td>
                                    <td>{{$user_data->phone_number ?? ''}}</td>
                                    <td>{{$user_data->email ?? ''}}</td>
                                    <td>{{date_format($user_data->created_at,'d-m-y' ?? '')}}</td>
                                    <td>
                                        @if($user_data->image)
                                            <img src="{{asset('public/storage/uploads/user-management/'.$user_data->image ?? '')}}">
                                        @else
                                            <img src="{{asset('public/storage/uploads/user-management/avtar.png')}}">
                                        @endif
                                    </td>
                                    <td>{{$user_data->dob ?? ''}}</td>
                                    <td>
                                        <label class="badge {{$user_data->status == 1 ? 'badge-success' : 'badge-danger'}}">{{$user_data->status == 1 ? 'Active' : 'Inactive'}}</label>
                                    </td>

                                    <td>
                                        <a class="btn btn-outline-success" href="{{route('admin.user.edit.view', ['id'=>base64_encode($user_data->id), 'page'=>request('page')])}}"> <i class="fa fa-pencil-square-o"></i>
                                                        Edit</a>
                                        <a class="btn btn-outline-danger" onclick="return confirm('Are you sure?')" href="{{route('admin.user.delete', ['id'=>base64_encode($user_data->id), 'page'=>request('page')])}}"> <i class="fa fa-trash"></i>
                                          Delete</a>
                                    </td>
                                </tr>
                            @empty
                            @endforelse
                            </tbody>
                            {{$user_list->links()}}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('scripts')
<script type="text/javascript">
$(document).ready( function () {
    var uri = window.location.toString();
    if (uri.indexOf("?") > 0) {
        var clean_uri = uri.substring(0, uri.indexOf("?"));
        window.history.replaceState({}, document.title, clean_uri);
    }

    $('#data-table-id').DataTable({
        "paging": false,
        columnDefs: [
            { orderable: false, targets:8 },
        ]
    });



    $('#from').datepicker({
        uiLibrary: 'bootstrap4'
    });

    $('#to').datepicker({
        uiLibrary: 'bootstrap4'
    });



});
</script>
@endsection